apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tomcat
  name: deployment-tomcat
spec:
  replicas: 4
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - image: nkw12345/argocd:latest
        name: tomcat
---
apiVersion: v1
kind: Service
metadata:
  name: svc-tomcat
spec:
  selector:
    app: tomcat
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
  clusterIP: 10.99.154.50
